# Display a box
print("Please enter a character for Beep's eyes")
eyes = input()

print("   ##########")
print(f"   # {eyes}    {eyes} #")
print("   #  ----  #")
print("   ##########")
print("       ##")
print("################")
print("#              #")
print("#              #")
print("#              #")
print("#              #")
print("################")