print("Enter a string:\t")
string = str(input())
print("Enter an integer:\t")
integer = int(input())
print("Enter a decimal number:\t")
decimal = float(input())
print("How long is the first line?\t")
line1 = int(input())
print("How long is the second line?\t")
line2 = int(input())
print("How long is the third line?\t")
line3 = int(input())
print(string * line1)
print(str(integer) * line2)
print(str(decimal) * line3)