print("Please enter the number of lives.")
lives = int(input())
print("\nPlease enter the energy level.")
energy = int(input())
print("\nPlease enter the shield level.")
shield = int(input())
print("\nHealth has been set")
print(f"\nLives:\t{'♥' * lives}")
print(f"Energy:\t{'♦' * energy}")
print(f"Shield:\t{'♦' * shield}")